"""PDFReader: high-level façade that ties all components together."""

from typing import Any, Dict, List, Optional

from langchain_core.documents import Document

from .config import Config
from .llm_interface import LLMInterface
from .pdf_processor import PDFProcessor
from .vector_store import VectorStore


class PDFReader:
    """End-to-end LLM-based PDF reader.

    Usage::

        reader = PDFReader(api_key="sk-...")
        reader.index("document.pdf")
        answer = reader.ask("What is the main topic?")
        summary = reader.summarize()
        results = reader.search("neural networks")
    """

    def __init__(
        self,
        api_key: Optional[str] = None,
        model: str = Config.OPENAI_MODEL,
        chunk_size: int = Config.CHUNK_SIZE,
        chunk_overlap: int = Config.CHUNK_OVERLAP,
    ):
        self._processor = PDFProcessor(
            chunk_size=chunk_size, chunk_overlap=chunk_overlap
        )
        self._vector_store = VectorStore(api_key=api_key)
        self._llm = LLMInterface(
            vector_store=self._vector_store,
            api_key=api_key,
            model=model,
        )
        self._documents: List[Document] = []

    # ------------------------------------------------------------------
    # Indexing
    # ------------------------------------------------------------------

    def index(self, pdf_path: str) -> int:
        """Load a PDF, chunk it, and build the semantic index.

        Args:
            pdf_path: Path to the PDF file.

        Returns:
            Number of chunks indexed.
        """
        self._documents = self._processor.load(pdf_path)
        chunks = self._processor.split(self._documents)
        self._vector_store.build(chunks)
        return len(chunks)

    def add_pdf(self, pdf_path: str) -> int:
        """Add another PDF to an existing index.

        Args:
            pdf_path: Path to the PDF file.

        Returns:
            Number of new chunks added.
        """
        new_docs = self._processor.load(pdf_path)
        self._documents.extend(new_docs)
        chunks = self._processor.split(new_docs)
        if not self._vector_store.is_ready:
            self._vector_store.build(chunks)
        else:
            self._vector_store.add_documents(chunks)
        return len(chunks)

    def save_index(self, directory: str) -> None:
        """Persist the current index to disk.

        Args:
            directory: Directory where the index will be saved.
        """
        self._vector_store.save(directory)

    def load_index(self, directory: str) -> None:
        """Load a previously saved index from disk.

        Args:
            directory: Directory containing the saved index.
        """
        self._vector_store.load(directory)

    # ------------------------------------------------------------------
    # Q&A
    # ------------------------------------------------------------------

    def ask(self, question: str, k: int = Config.SEARCH_TOP_K) -> str:
        """Answer a question about the indexed PDF content.

        Args:
            question: Natural-language question.
            k: Number of context chunks to retrieve.

        Returns:
            Answer string generated by the LLM.
        """
        result = self._llm.answer(question, k=k)
        return result.get("result", "")

    def ask_with_sources(
        self, question: str, k: int = Config.SEARCH_TOP_K
    ) -> Dict[str, Any]:
        """Answer a question and return the source document chunks used.

        Args:
            question: Natural-language question.
            k: Number of context chunks to retrieve.

        Returns:
            Dict with 'answer' and 'sources' keys.
        """
        result = self._llm.answer(question, k=k)
        sources = [
            {
                "content": doc.page_content,
                "metadata": doc.metadata,
            }
            for doc in result.get("source_documents", [])
        ]
        return {"answer": result.get("result", ""), "sources": sources}

    # ------------------------------------------------------------------
    # Summarization
    # ------------------------------------------------------------------

    def summarize(self) -> str:
        """Summarize all indexed PDF content.

        Returns:
            Summary string.

        Raises:
            RuntimeError: If no PDF has been indexed.
        """
        if not self._documents:
            raise RuntimeError("No PDF has been indexed. Call index() first.")
        return self._llm.summarize(self._documents)

    def summarize_page(self, page_number: int) -> str:
        """Summarize a specific page of the indexed PDF.

        Args:
            page_number: 0-based page index.

        Returns:
            Summary of the requested page.

        Raises:
            RuntimeError: If no PDF has been indexed.
            IndexError: If the page number is out of range.
        """
        if not self._documents:
            raise RuntimeError("No PDF has been indexed. Call index() first.")
        if page_number < 0 or page_number >= len(self._documents):
            raise IndexError(
                f"Page {page_number} out of range "
                f"(document has {len(self._documents)} pages)."
            )
        return self._llm.summarize([self._documents[page_number]])

    # ------------------------------------------------------------------
    # Semantic search
    # ------------------------------------------------------------------

    def search(
        self, query: str, k: int = Config.SEARCH_TOP_K
    ) -> List[Dict[str, Any]]:
        """Perform a semantic search over the indexed PDF content.

        Args:
            query: Natural-language search query.
            k: Number of results to return.

        Returns:
            List of result dicts with 'content', 'score', and 'metadata' keys.
        """
        return self._llm.search(query, k=k)

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    @property
    def full_text(self) -> str:
        """Return the full extracted text of all indexed documents."""
        return PDFProcessor.extract_text(self._documents)

    @property
    def page_count(self) -> int:
        """Number of pages in the currently loaded document(s)."""
        return len(self._documents)
